# -*- coding: utf-8 -*-

#CONSTANTES

ANCHO_XOGO = 1000
ALTO_XOGO = 1000

ANCHO_VENTANA_INICIAL = 600
ALTO_VENTANA_INICIAL = 500

ANCHO_VENTANA = ANCHO_VENTANA_INICIAL
ALTO_VENTANA = ALTO_VENTANA_INICIAL

NUMERO_CADROS_ANCHO = 100
NUMERO_CADROS_ALTO = 100

ANCHO_CADRO = ANCHO_VENTANA / NUMERO_CADROS_ANCHO
ALTO_CADRO = ALTO_VENTANA / NUMERO_CADROS_ALTO

MARCO_VENTANA_LATERAL = ANCHO_CADRO * 5
MARCO_VENTANA_VERTICAL = ALTO_CADRO * 2

ANCHO_VENTANA_REAL = ANCHO_VENTANA - MARCO_VENTANA_LATERAL*2
ALTO_VENTANA_REAL = ALTO_VENTANA - MARCO_VENTANA_VERTICAL*2	

ANCHO_XOGO_REAL = ANCHO_XOGO - MARCO_VENTANA_LATERAL*2
ALTO_XOGO_REAL = ALTO_XOGO - MARCO_VENTANA_VERTICAL*2

NUMERO_CADROS_ANCHO_XOGO = int(ANCHO_XOGO_REAL / ANCHO_CADRO)
NUMERO_CADROS_ALTO_XOGO = int(ALTO_XOGO_REAL / ALTO_CADRO)

NUMERO_CADROS_TOTALES_VENTANA = NUMERO_CADROS_ANCHO*NUMERO_CADROS_ALTO
NUMERO_CADROS_TOTALES_XOGO = NUMERO_CADROS_ANCHO_XOGO*NUMERO_CADROS_ALTO_XOGO

ANCHO_PJ = ANCHO_CADRO * 3
ALTO_PJ = ALTO_CADRO * 5

VELOCIDADE_PJ = ANCHO_CADRO / 1.5

LISTA_CADROS = []

for i in range(NUMERO_CADROS_TOTALES_XOGO):
	LISTA_CADROS.append(0)